### ISSUE TITLE
npm install critical security warning

### ISSUE THREAD

**Issue by tailorvj** [planetoftheweb/electron#4]
Hi, after npm install, there is a critical security warning about some of the modules used in your solution. I tried npm audit fix and npm audit fix --force to no avail. 

![screen shot 2018-11-29 at 20 27 52](https://user-images.githubusercontent.com/1202692/49222084-e21f6900-f415-11e8-8411-7c88b6c9c3ff.png)

Please update your solution. 

Kind regards,
Tailor

**Comment by planetoftheweb** [comment]
This whole course is being redone. Repos for courses are a snapshot in time and use the modules that were used at the time of recording.
